openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
  description: Order endpoints
paths:
  /api/orders:
    post:
      summary: Create a fixed price order
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                quantity:
                  type: integer
                deliveryType:
                  type: string
                  enum: [DELIVERY, PICKUP]
                addressId:
                  type: integer
      responses:
        '200':
          description: Order created
    get:
      summary: Get all orders for the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of orders
  /api/orders/{id}:
    get:
      summary: Get order by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Order details
    delete:
      summary: Cancel an order
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Order cancelled
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 